title: Timetable Bot
remote_theme: pmarsceill/just-the-docs

search_enabled: false

heading_anchors: true

aux_links:
  "Академия гражданской защиты МЧС России":
    - "https://amchs.ru"

footer_content: "Разработчик - студент 307 группы Насонов Никита"

color_scheme: nil
