title: Timetable Bot
remote_theme: pmarsceill/just-the-docs

search_enabled: false

heading_anchors: true

aux_links:
  "Академия гражданской защиты МЧС России":
    - "https://amchs.ru"
  "Сообщество Timetable Bot":
    - "https://vk.com/bot_agz"
  "Включить темный режим":
    - <button class="btn js-toggle-dark-mode">Preview dark color scheme</button>

      <script>
      const toggleDarkMode = document.querySelector('.js-toggle-dark-mode');

      jtd.addEvent(toggleDarkMode, 'click', function(){
      if (jtd.getTheme() === 'dark') {
      jtd.setTheme('light');
      toggleDarkMode.textContent = 'Preview dark color scheme';
      } else {
      jtd.setTheme('dark');
      toggleDarkMode.textContent = 'Return to the light side';
      }
      });
      </script>


back_to_top: true
back_to_top_text: "Вернуться наверх"

color_scheme: nil
