title: Timetable Bot
remote_theme: pmarsceill/just-the-docs

search_enabled: false

heading_anchors: true

aux_links:
  "Академия гражданской защиты МЧС России":
    - "https://amchs.ru"
  "Сообщество Timetable Bot":
    - "https://vk.com/bot_agz"

back_to_top: true
back_to_top_text: "Вернуться наверх"

color_scheme: nil
