remote_theme: pmarsceill/just-the-docs

title: TimetableBot
logo: "icon-main.png"

search_enabled: true
search:
  heading_level: 1
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Enable or disable heading anchors
heading_anchors: true

nav_sort: case_sensitive

back_to_top: true
back_to_top_text: "Вернуться наверх"

footer_content: "Разработано для [Академии гражданской защиты МЧС России](https://amchs.ru) студентом 307 группы Насоновым Никитой"

color_scheme: nil
