title: Timetable Bot
remote_theme: pmarsceill/just-the-docs

search_enabled: true
search:
  heading_level: 1
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

heading_anchors: true

nav_sort: case_sensitive

footer_content: "Разработчик - студент 307 группы Насонов Никита"

gh_edit_link: true
gh_edit_link_text: "Академия гражданской защиты МЧС России"
gh_edit_repository: "https://amchs.ru"

color_scheme: nil
